# Generated by Django 4.2.11 on 2024-04-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('author', 'author'), ('family', 'family'), ('friends', 'friends'), ('public', 'public')], default='author', max_length=100),
        ),
    ]
