# Generated by Django 4.2.11 on 2024-04-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='author',
        ),
        migrations.RemoveField(
            model_name='images',
            name='author',
        ),
    ]
