# Generated by Django 4.2.11 on 2024-04-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_picha'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
